services:
  accounts:
    image: "amandea/accounts:s4"
    container_name: accounts-ms
    ports:
      - "9090:9090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - amandea
  loans:
    image: "amandea/loans:s4"
    container_name: loans-ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - amandea
  cards:
    image: "amandea/cards:s4"
    container_name: cards-ms
    ports:
      - "8070:8070"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - amandea
networks:
  amandea:
    driver: "bridge"